kind: pipeline
name: Test

steps:
  - name: mix
    image: elixir:1.8.1-alpine
    environment:
      DB_HOST: mysql
    commands:
      - apk add --no-cache gcc g++ git imagemagick libc-dev libmcrypt-dev make
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

  - name: node
    image: amd64/node:10.16.0@sha256:2901e1fa26d1f430c93178cef3e3c024ec71c66f31c5decec45c4f6e9e164ce4
    commands:
      - npm install
      - npm test

services:
  - name: mysql
    image: mysql:5.7.24
    ports:
      - 3306

  - name: redis
    image: redis:alpine
    ports:
      - 6379
