kind: pipeline
name: Test

steps:
  - name: mix
    image: elixir:1.9.1-alpine@sha256:74d35e9c87122e517235651bb0be2a68972ad36b3e40fabb198ca5b4e472bd85
    environment:
      DB_HOST: mysql
    commands:
      - apk add --no-cache gcc g++ git imagemagick libc-dev libmcrypt-dev make
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

  - name: node
    image: amd64/node:10.0.0@sha256:36adc17e9cceab32179d3314da9cb9c737ffb11f0de4e688f407ad6d9ca32201
    commands:
      - npm install
      - npm test

services:
  - name: mysql
    image: mysql:5.7.24@sha256:bf17a7109057494c45fba5aab7fc805ca00ac1eef638dfdd42b38d5a7190c9bb
    ports:
      - 3306

  - name: redis
    image: redis:alpine@sha256:4a09815a6755e372b9ab96a0ed3229cbb34a8d1998ef18f5072278ff2cb86923
    ports:
      - 6379
