kind: pipeline
name: Test

steps:
  - name: mix
    image: elixir:1.8.1-alpine@sha256:13713e199a4944b342d1546d33c33e823cf471643181e102a821998ecd85ce11
    environment:
      DB_HOST: mysql
    commands:
      - apk add --no-cache gcc g++ git imagemagick libc-dev libmcrypt-dev make
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

  - name: node
    image: amd64/node:10.0.0@sha256:5082d4db78ee2d24f72b25eb75537f2e19c49f04a595378d1ae8814d6f2fbf28
    commands:
      - npm install
      - npm test

services:
  - name: mysql
    image: mysql:5.7.24@sha256:bf17a7109057494c45fba5aab7fc805ca00ac1eef638dfdd42b38d5a7190c9bb
    ports:
      - 3306

  - name: redis
    image: redis:alpine@sha256:4a09815a6755e372b9ab96a0ed3229cbb34a8d1998ef18f5072278ff2cb86923
    ports:
      - 6379
